// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)

// SavedFilter is the predicate function for savedfilter builders.
type SavedFilter func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
