-- create "chunks" table
CREATE TABLE "chunks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "source_type" character varying NOT NULL,
  "source_id" bigint NOT NULL,
  "chunk_index" bigint NOT NULL DEFAULT 0,
  "chunk_hash" character varying NOT NULL,
  "content" text NOT NULL,
  "embedding" halfvec(768) NULL,
  "project" character varying NULL,
  "tags" jsonb NULL,
  "item_due_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "chunk_chunk_hash" to table: "chunks"
CREATE INDEX "chunk_chunk_hash" ON "chunks" ("chunk_hash");
-- create index "chunk_source_type_item_due_at" to table: "chunks"
CREATE INDEX "chunk_source_type_item_due_at" ON "chunks" ("source_type", "item_due_at");
-- create index "chunk_source_type_source_id_chunk_index" to table: "chunks"
CREATE UNIQUE INDEX "chunk_source_type_source_id_chunk_index" ON "chunks" ("source_type", "source_id", "chunk_index");
-- create "notes" table
CREATE TABLE "notes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "body_md" text NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create "saved_filters" table
CREATE TABLE "saved_filters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "query" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "saved_filters_name_key" to table: "saved_filters"
CREATE UNIQUE INDEX "saved_filters_name_key" ON "saved_filters" ("name");
-- create "tags" table
CREATE TABLE "tags" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "kind" character varying NOT NULL DEFAULT 'tag',
  "description" text NULL,
  "archived_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "tag_children" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tags_tags_children" FOREIGN KEY ("tag_children") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- create index "tag_kind" to table: "tags"
CREATE INDEX "tag_kind" ON "tags" ("kind");
-- create index "tag_name_kind" to table: "tags"
CREATE UNIQUE INDEX "tag_name_kind" ON "tags" ("name", "kind");
-- create "note_tags" table
CREATE TABLE "note_tags" (
  "note_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  PRIMARY KEY ("note_id", "tag_id"),
  CONSTRAINT "note_tags_note_id" FOREIGN KEY ("note_id") REFERENCES "notes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "note_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- create "tasks" table
CREATE TABLE "tasks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "body_md" text NULL,
  "status" character varying NOT NULL DEFAULT 'open',
  "priority" bigint NOT NULL DEFAULT 0,
  "due_at" timestamptz NULL,
  "defer_at" timestamptz NULL,
  "completed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "task_project" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tasks_tags_project" FOREIGN KEY ("task_project") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- create index "task_defer_at" to table: "tasks"
CREATE INDEX "task_defer_at" ON "tasks" ("defer_at");
-- create index "task_due_at" to table: "tasks"
CREATE INDEX "task_due_at" ON "tasks" ("due_at");
-- create index "task_status" to table: "tasks"
CREATE INDEX "task_status" ON "tasks" ("status");
-- create "task_tags" table
CREATE TABLE "task_tags" (
  "task_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  PRIMARY KEY ("task_id", "tag_id"),
  CONSTRAINT "task_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "task_tags_task_id" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
