// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chunk type in the database.
	Label = "chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldChunkIndex holds the string denoting the chunk_index field in the database.
	FieldChunkIndex = "chunk_index"
	// FieldChunkHash holds the string denoting the chunk_hash field in the database.
	FieldChunkHash = "chunk_hash"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldItemDueAt holds the string denoting the item_due_at field in the database.
	FieldItemDueAt = "item_due_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the chunk in the database.
	Table = "chunks"
)

// Columns holds all SQL columns for chunk fields.
var Columns = []string{
	FieldID,
	FieldSourceType,
	FieldSourceID,
	FieldChunkIndex,
	FieldChunkHash,
	FieldContent,
	FieldEmbedding,
	FieldProject,
	FieldTags,
	FieldItemDueAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChunkIndex holds the default value on creation for the "chunk_index" field.
	DefaultChunkIndex int
	// ChunkHashValidator is a validator for the "chunk_hash" field. It is called by the builders before save.
	ChunkHashValidator func(string) error
	// ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	ProjectValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// SourceType defines the type for the "source_type" enum field.
type SourceType string

// SourceType values.
const (
	SourceTypeTask SourceType = "task"
	SourceTypeNote SourceType = "note"
	SourceTypeTag  SourceType = "tag"
)

func (st SourceType) String() string {
	return string(st)
}

// SourceTypeValidator is a validator for the "source_type" field enum values. It is called by the builders before save.
func SourceTypeValidator(st SourceType) error {
	switch st {
	case SourceTypeTask, SourceTypeNote, SourceTypeTag:
		return nil
	default:
		return fmt.Errorf("chunk: invalid enum value for source_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the Chunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByChunkIndex orders the results by the chunk_index field.
func ByChunkIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkIndex, opts...).ToFunc()
}

// ByChunkHash orders the results by the chunk_hash field.
func ByChunkHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkHash, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByEmbedding orders the results by the embedding field.
func ByEmbedding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbedding, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByItemDueAt orders the results by the item_due_at field.
func ByItemDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemDueAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
