// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bamarler/universe-647/sophon/internal/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldSourceID, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkHash applies equality check predicate on the "chunk_hash" field. It's identical to ChunkHashEQ.
func ChunkHash(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkHash, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldContent, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbedding, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldProject, v))
}

// ItemDueAt applies equality check predicate on the "item_due_at" field. It's identical to ItemDueAtEQ.
func ItemDueAt(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldItemDueAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldSourceID, v))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ChunkHashEQ applies the EQ predicate on the "chunk_hash" field.
func ChunkHashEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkHash, v))
}

// ChunkHashNEQ applies the NEQ predicate on the "chunk_hash" field.
func ChunkHashNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldChunkHash, v))
}

// ChunkHashIn applies the In predicate on the "chunk_hash" field.
func ChunkHashIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldChunkHash, vs...))
}

// ChunkHashNotIn applies the NotIn predicate on the "chunk_hash" field.
func ChunkHashNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldChunkHash, vs...))
}

// ChunkHashGT applies the GT predicate on the "chunk_hash" field.
func ChunkHashGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldChunkHash, v))
}

// ChunkHashGTE applies the GTE predicate on the "chunk_hash" field.
func ChunkHashGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldChunkHash, v))
}

// ChunkHashLT applies the LT predicate on the "chunk_hash" field.
func ChunkHashLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldChunkHash, v))
}

// ChunkHashLTE applies the LTE predicate on the "chunk_hash" field.
func ChunkHashLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldChunkHash, v))
}

// ChunkHashContains applies the Contains predicate on the "chunk_hash" field.
func ChunkHashContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldChunkHash, v))
}

// ChunkHashHasPrefix applies the HasPrefix predicate on the "chunk_hash" field.
func ChunkHashHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldChunkHash, v))
}

// ChunkHashHasSuffix applies the HasSuffix predicate on the "chunk_hash" field.
func ChunkHashHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldChunkHash, v))
}

// ChunkHashEqualFold applies the EqualFold predicate on the "chunk_hash" field.
func ChunkHashEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldChunkHash, v))
}

// ChunkHashContainsFold applies the ContainsFold predicate on the "chunk_hash" field.
func ChunkHashContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldChunkHash, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldContent, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.HalfVector) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldEmbedding, v))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldEmbedding))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectIsNil applies the IsNil predicate on the "project" field.
func ProjectIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldProject))
}

// ProjectNotNil applies the NotNil predicate on the "project" field.
func ProjectNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldProject))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldProject, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldTags))
}

// ItemDueAtEQ applies the EQ predicate on the "item_due_at" field.
func ItemDueAtEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldItemDueAt, v))
}

// ItemDueAtNEQ applies the NEQ predicate on the "item_due_at" field.
func ItemDueAtNEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldItemDueAt, v))
}

// ItemDueAtIn applies the In predicate on the "item_due_at" field.
func ItemDueAtIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldItemDueAt, vs...))
}

// ItemDueAtNotIn applies the NotIn predicate on the "item_due_at" field.
func ItemDueAtNotIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldItemDueAt, vs...))
}

// ItemDueAtGT applies the GT predicate on the "item_due_at" field.
func ItemDueAtGT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldItemDueAt, v))
}

// ItemDueAtGTE applies the GTE predicate on the "item_due_at" field.
func ItemDueAtGTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldItemDueAt, v))
}

// ItemDueAtLT applies the LT predicate on the "item_due_at" field.
func ItemDueAtLT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldItemDueAt, v))
}

// ItemDueAtLTE applies the LTE predicate on the "item_due_at" field.
func ItemDueAtLTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldItemDueAt, v))
}

// ItemDueAtIsNil applies the IsNil predicate on the "item_due_at" field.
func ItemDueAtIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldItemDueAt))
}

// ItemDueAtNotNil applies the NotNil predicate on the "item_due_at" field.
func ItemDueAtNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldItemDueAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.NotPredicates(p))
}
