// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_type", Type: field.TypeEnum, Enums: []string{"task", "note", "tag"}},
		{Name: "source_id", Type: field.TypeInt},
		{Name: "chunk_index", Type: field.TypeInt, Default: 0},
		{Name: "chunk_hash", Type: field.TypeString, Size: 64},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "embedding", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "halfvec(768)"}},
		{Name: "project", Type: field.TypeString, Nullable: true, Size: 120},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "item_due_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "chunk_source_type_source_id_chunk_index",
				Unique:  true,
				Columns: []*schema.Column{ChunksColumns[1], ChunksColumns[2], ChunksColumns[3]},
			},
			{
				Name:    "chunk_source_type_item_due_at",
				Unique:  false,
				Columns: []*schema.Column{ChunksColumns[1], ChunksColumns[9]},
			},
			{
				Name:    "chunk_chunk_hash",
				Unique:  false,
				Columns: []*schema.Column{ChunksColumns[4]},
			},
		},
	}
	// NotesColumns holds the columns for the "notes" table.
	NotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 500},
		{Name: "body_md", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NotesTable holds the schema information for the "notes" table.
	NotesTable = &schema.Table{
		Name:       "notes",
		Columns:    NotesColumns,
		PrimaryKey: []*schema.Column{NotesColumns[0]},
	}
	// SavedFiltersColumns holds the columns for the "saved_filters" table.
	SavedFiltersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 120},
		{Name: "query", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SavedFiltersTable holds the schema information for the "saved_filters" table.
	SavedFiltersTable = &schema.Table{
		Name:       "saved_filters",
		Columns:    SavedFiltersColumns,
		PrimaryKey: []*schema.Column{SavedFiltersColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 120},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"project", "context", "tag"}, Default: "tag"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tag_children", Type: field.TypeInt, Nullable: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_tags_children",
				Columns:    []*schema.Column{TagsColumns[7]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tag_name_kind",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[1], TagsColumns[2]},
			},
			{
				Name:    "tag_kind",
				Unique:  false,
				Columns: []*schema.Column{TagsColumns[2]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 500},
		{Name: "body_md", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "done"}, Default: "open"},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "due_at", Type: field.TypeTime, Nullable: true},
		{Name: "defer_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "task_project", Type: field.TypeInt, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_tags_project",
				Columns:    []*schema.Column{TasksColumns[10]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "task_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3]},
			},
			{
				Name:    "task_due_at",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[5]},
			},
			{
				Name:    "task_defer_at",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[6]},
			},
		},
	}
	// NoteTagsColumns holds the columns for the "note_tags" table.
	NoteTagsColumns = []*schema.Column{
		{Name: "note_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// NoteTagsTable holds the schema information for the "note_tags" table.
	NoteTagsTable = &schema.Table{
		Name:       "note_tags",
		Columns:    NoteTagsColumns,
		PrimaryKey: []*schema.Column{NoteTagsColumns[0], NoteTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_tags_note_id",
				Columns:    []*schema.Column{NoteTagsColumns[0]},
				RefColumns: []*schema.Column{NotesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "note_tags_tag_id",
				Columns:    []*schema.Column{NoteTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TaskTagsColumns holds the columns for the "task_tags" table.
	TaskTagsColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// TaskTagsTable holds the schema information for the "task_tags" table.
	TaskTagsTable = &schema.Table{
		Name:       "task_tags",
		Columns:    TaskTagsColumns,
		PrimaryKey: []*schema.Column{TaskTagsColumns[0], TaskTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_tags_task_id",
				Columns:    []*schema.Column{TaskTagsColumns[0]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "task_tags_tag_id",
				Columns:    []*schema.Column{TaskTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
		NotesTable,
		SavedFiltersTable,
		TagsTable,
		TasksTable,
		NoteTagsTable,
		TaskTagsTable,
	}
)

func init() {
	TagsTable.ForeignKeys[0].RefTable = TagsTable
	TasksTable.ForeignKeys[0].RefTable = TagsTable
	NoteTagsTable.ForeignKeys[0].RefTable = NotesTable
	NoteTagsTable.ForeignKeys[1].RefTable = TagsTable
	TaskTagsTable.ForeignKeys[0].RefTable = TasksTable
	TaskTagsTable.ForeignKeys[1].RefTable = TagsTable
}
