// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bamarler/universe-647/sophon/internal/ent/chunk"
	pgvector "github.com/pgvector/pgvector-go"
)

// ChunkCreate is the builder for creating a Chunk entity.
type ChunkCreate struct {
	config
	mutation *ChunkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceType sets the "source_type" field.
func (_c *ChunkCreate) SetSourceType(v chunk.SourceType) *ChunkCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ChunkCreate) SetSourceID(v int) *ChunkCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetChunkIndex sets the "chunk_index" field.
func (_c *ChunkCreate) SetChunkIndex(v int) *ChunkCreate {
	_c.mutation.SetChunkIndex(v)
	return _c
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableChunkIndex(v *int) *ChunkCreate {
	if v != nil {
		_c.SetChunkIndex(*v)
	}
	return _c
}

// SetChunkHash sets the "chunk_hash" field.
func (_c *ChunkCreate) SetChunkHash(v string) *ChunkCreate {
	_c.mutation.SetChunkHash(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChunkCreate) SetContent(v string) *ChunkCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *ChunkCreate) SetEmbedding(v pgvector.HalfVector) *ChunkCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableEmbedding(v *pgvector.HalfVector) *ChunkCreate {
	if v != nil {
		_c.SetEmbedding(*v)
	}
	return _c
}

// SetProject sets the "project" field.
func (_c *ChunkCreate) SetProject(v string) *ChunkCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableProject(v *string) *ChunkCreate {
	if v != nil {
		_c.SetProject(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ChunkCreate) SetTags(v []string) *ChunkCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetItemDueAt sets the "item_due_at" field.
func (_c *ChunkCreate) SetItemDueAt(v time.Time) *ChunkCreate {
	_c.mutation.SetItemDueAt(v)
	return _c
}

// SetNillableItemDueAt sets the "item_due_at" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableItemDueAt(v *time.Time) *ChunkCreate {
	if v != nil {
		_c.SetItemDueAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChunkCreate) SetCreatedAt(v time.Time) *ChunkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableCreatedAt(v *time.Time) *ChunkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChunkCreate) SetUpdatedAt(v time.Time) *ChunkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableUpdatedAt(v *time.Time) *ChunkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ChunkMutation object of the builder.
func (_c *ChunkCreate) Mutation() *ChunkMutation {
	return _c.mutation
}

// Save creates the Chunk in the database.
func (_c *ChunkCreate) Save(ctx context.Context) (*Chunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChunkCreate) SaveX(ctx context.Context) *Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChunkCreate) defaults() {
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		v := chunk.DefaultChunkIndex
		_c.mutation.SetChunkIndex(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chunk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chunk.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChunkCreate) check() error {
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "Chunk.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := chunk.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Chunk.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "Chunk.source_id"`)}
	}
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "Chunk.chunk_index"`)}
	}
	if _, ok := _c.mutation.ChunkHash(); !ok {
		return &ValidationError{Name: "chunk_hash", err: errors.New(`ent: missing required field "Chunk.chunk_hash"`)}
	}
	if v, ok := _c.mutation.ChunkHash(); ok {
		if err := chunk.ChunkHashValidator(v); err != nil {
			return &ValidationError{Name: "chunk_hash", err: fmt.Errorf(`ent: validator failed for field "Chunk.chunk_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Chunk.content"`)}
	}
	if v, ok := _c.mutation.Project(); ok {
		if err := chunk.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "Chunk.project": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chunk.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chunk.updated_at"`)}
	}
	return nil
}

func (_c *ChunkCreate) sqlSave(ctx context.Context) (*Chunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChunkCreate) createSpec() (*Chunk, *sqlgraph.CreateSpec) {
	var (
		_node = &Chunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chunk.Table, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(chunk.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(chunk.FieldSourceID, field.TypeInt, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.ChunkIndex(); ok {
		_spec.SetField(chunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := _c.mutation.ChunkHash(); ok {
		_spec.SetField(chunk.FieldChunkHash, field.TypeString, value)
		_node.ChunkHash = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chunk.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(chunk.FieldEmbedding, field.TypeOther, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(chunk.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(chunk.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.ItemDueAt(); ok {
		_spec.SetField(chunk.FieldItemDueAt, field.TypeTime, value)
		_node.ItemDueAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chunk.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.Create().
//		SetSourceType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetSourceType(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertOne {
	_c.conflict = opts
	return &ChunkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflictColumns(columns ...string) *ChunkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertOne{
		create: _c,
	}
}

type (
	// ChunkUpsertOne is the builder for "upsert"-ing
	//  one Chunk node.
	ChunkUpsertOne struct {
		create *ChunkCreate
	}

	// ChunkUpsert is the "OnConflict" setter.
	ChunkUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceType sets the "source_type" field.
func (u *ChunkUpsert) SetSourceType(v chunk.SourceType) *ChunkUpsert {
	u.Set(chunk.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateSourceType() *ChunkUpsert {
	u.SetExcluded(chunk.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *ChunkUpsert) SetSourceID(v int) *ChunkUpsert {
	u.Set(chunk.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateSourceID() *ChunkUpsert {
	u.SetExcluded(chunk.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *ChunkUpsert) AddSourceID(v int) *ChunkUpsert {
	u.Add(chunk.FieldSourceID, v)
	return u
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsert) SetChunkIndex(v int) *ChunkUpsert {
	u.Set(chunk.FieldChunkIndex, v)
	return u
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateChunkIndex() *ChunkUpsert {
	u.SetExcluded(chunk.FieldChunkIndex)
	return u
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsert) AddChunkIndex(v int) *ChunkUpsert {
	u.Add(chunk.FieldChunkIndex, v)
	return u
}

// SetChunkHash sets the "chunk_hash" field.
func (u *ChunkUpsert) SetChunkHash(v string) *ChunkUpsert {
	u.Set(chunk.FieldChunkHash, v)
	return u
}

// UpdateChunkHash sets the "chunk_hash" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateChunkHash() *ChunkUpsert {
	u.SetExcluded(chunk.FieldChunkHash)
	return u
}

// SetContent sets the "content" field.
func (u *ChunkUpsert) SetContent(v string) *ChunkUpsert {
	u.Set(chunk.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateContent() *ChunkUpsert {
	u.SetExcluded(chunk.FieldContent)
	return u
}

// SetEmbedding sets the "embedding" field.
func (u *ChunkUpsert) SetEmbedding(v pgvector.HalfVector) *ChunkUpsert {
	u.Set(chunk.FieldEmbedding, v)
	return u
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateEmbedding() *ChunkUpsert {
	u.SetExcluded(chunk.FieldEmbedding)
	return u
}

// ClearEmbedding clears the value of the "embedding" field.
func (u *ChunkUpsert) ClearEmbedding() *ChunkUpsert {
	u.SetNull(chunk.FieldEmbedding)
	return u
}

// SetProject sets the "project" field.
func (u *ChunkUpsert) SetProject(v string) *ChunkUpsert {
	u.Set(chunk.FieldProject, v)
	return u
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateProject() *ChunkUpsert {
	u.SetExcluded(chunk.FieldProject)
	return u
}

// ClearProject clears the value of the "project" field.
func (u *ChunkUpsert) ClearProject() *ChunkUpsert {
	u.SetNull(chunk.FieldProject)
	return u
}

// SetTags sets the "tags" field.
func (u *ChunkUpsert) SetTags(v []string) *ChunkUpsert {
	u.Set(chunk.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateTags() *ChunkUpsert {
	u.SetExcluded(chunk.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *ChunkUpsert) ClearTags() *ChunkUpsert {
	u.SetNull(chunk.FieldTags)
	return u
}

// SetItemDueAt sets the "item_due_at" field.
func (u *ChunkUpsert) SetItemDueAt(v time.Time) *ChunkUpsert {
	u.Set(chunk.FieldItemDueAt, v)
	return u
}

// UpdateItemDueAt sets the "item_due_at" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateItemDueAt() *ChunkUpsert {
	u.SetExcluded(chunk.FieldItemDueAt)
	return u
}

// ClearItemDueAt clears the value of the "item_due_at" field.
func (u *ChunkUpsert) ClearItemDueAt() *ChunkUpsert {
	u.SetNull(chunk.FieldItemDueAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsert) SetUpdatedAt(v time.Time) *ChunkUpsert {
	u.Set(chunk.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateUpdatedAt() *ChunkUpsert {
	u.SetExcluded(chunk.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChunkUpsertOne) UpdateNewValues() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chunk.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChunkUpsertOne) Ignore() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertOne) DoNothing() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreate.OnConflict
// documentation for more info.
func (u *ChunkUpsertOne) Update(set func(*ChunkUpsert)) *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ChunkUpsertOne) SetSourceType(v chunk.SourceType) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateSourceType() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ChunkUpsertOne) SetSourceID(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *ChunkUpsertOne) AddSourceID(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateSourceID() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSourceID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsertOne) SetChunkIndex(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsertOne) AddChunkIndex(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateChunkIndex() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetChunkHash sets the "chunk_hash" field.
func (u *ChunkUpsertOne) SetChunkHash(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkHash(v)
	})
}

// UpdateChunkHash sets the "chunk_hash" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateChunkHash() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkHash()
	})
}

// SetContent sets the "content" field.
func (u *ChunkUpsertOne) SetContent(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateContent() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateContent()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *ChunkUpsertOne) SetEmbedding(v pgvector.HalfVector) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateEmbedding() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateEmbedding()
	})
}

// ClearEmbedding clears the value of the "embedding" field.
func (u *ChunkUpsertOne) ClearEmbedding() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearEmbedding()
	})
}

// SetProject sets the "project" field.
func (u *ChunkUpsertOne) SetProject(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateProject() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *ChunkUpsertOne) ClearProject() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearProject()
	})
}

// SetTags sets the "tags" field.
func (u *ChunkUpsertOne) SetTags(v []string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateTags() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *ChunkUpsertOne) ClearTags() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTags()
	})
}

// SetItemDueAt sets the "item_due_at" field.
func (u *ChunkUpsertOne) SetItemDueAt(v time.Time) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetItemDueAt(v)
	})
}

// UpdateItemDueAt sets the "item_due_at" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateItemDueAt() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateItemDueAt()
	})
}

// ClearItemDueAt clears the value of the "item_due_at" field.
func (u *ChunkUpsertOne) ClearItemDueAt() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearItemDueAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsertOne) SetUpdatedAt(v time.Time) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateUpdatedAt() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChunkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChunkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChunkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChunkCreateBulk is the builder for creating many Chunk entities in bulk.
type ChunkCreateBulk struct {
	config
	err      error
	builders []*ChunkCreate
	conflict []sql.ConflictOption
}

// Save creates the Chunk entities in the database.
func (_c *ChunkCreateBulk) Save(ctx context.Context) ([]*Chunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChunkCreateBulk) SaveX(ctx context.Context) []*Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetSourceType(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertBulk {
	_c.conflict = opts
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflictColumns(columns ...string) *ChunkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// ChunkUpsertBulk is the builder for "upsert"-ing
// a bulk of Chunk nodes.
type ChunkUpsertBulk struct {
	create *ChunkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChunkUpsertBulk) UpdateNewValues() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chunk.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChunkUpsertBulk) Ignore() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertBulk) DoNothing() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreateBulk.OnConflict
// documentation for more info.
func (u *ChunkUpsertBulk) Update(set func(*ChunkUpsert)) *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ChunkUpsertBulk) SetSourceType(v chunk.SourceType) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateSourceType() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ChunkUpsertBulk) SetSourceID(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *ChunkUpsertBulk) AddSourceID(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateSourceID() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSourceID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsertBulk) SetChunkIndex(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsertBulk) AddChunkIndex(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateChunkIndex() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetChunkHash sets the "chunk_hash" field.
func (u *ChunkUpsertBulk) SetChunkHash(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkHash(v)
	})
}

// UpdateChunkHash sets the "chunk_hash" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateChunkHash() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkHash()
	})
}

// SetContent sets the "content" field.
func (u *ChunkUpsertBulk) SetContent(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateContent() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateContent()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *ChunkUpsertBulk) SetEmbedding(v pgvector.HalfVector) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateEmbedding() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateEmbedding()
	})
}

// ClearEmbedding clears the value of the "embedding" field.
func (u *ChunkUpsertBulk) ClearEmbedding() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearEmbedding()
	})
}

// SetProject sets the "project" field.
func (u *ChunkUpsertBulk) SetProject(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateProject() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *ChunkUpsertBulk) ClearProject() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearProject()
	})
}

// SetTags sets the "tags" field.
func (u *ChunkUpsertBulk) SetTags(v []string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateTags() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *ChunkUpsertBulk) ClearTags() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTags()
	})
}

// SetItemDueAt sets the "item_due_at" field.
func (u *ChunkUpsertBulk) SetItemDueAt(v time.Time) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetItemDueAt(v)
	})
}

// UpdateItemDueAt sets the "item_due_at" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateItemDueAt() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateItemDueAt()
	})
}

// ClearItemDueAt clears the value of the "item_due_at" field.
func (u *ChunkUpsertBulk) ClearItemDueAt() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearItemDueAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsertBulk) SetUpdatedAt(v time.Time) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateUpdatedAt() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChunkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChunkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
