// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bamarler/universe-647/sophon/internal/ent/chunk"
	"github.com/bamarler/universe-647/sophon/internal/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ChunkUpdate is the builder for updating Chunk entities.
type ChunkUpdate struct {
	config
	hooks    []Hook
	mutation *ChunkMutation
}

// Where appends a list predicates to the ChunkUpdate builder.
func (_u *ChunkUpdate) Where(ps ...predicate.Chunk) *ChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ChunkUpdate) SetSourceType(v chunk.SourceType) *ChunkUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableSourceType(v *chunk.SourceType) *ChunkUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ChunkUpdate) SetSourceID(v int) *ChunkUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableSourceID(v *int) *ChunkUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ChunkUpdate) AddSourceID(v int) *ChunkUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *ChunkUpdate) SetChunkIndex(v int) *ChunkUpdate {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableChunkIndex(v *int) *ChunkUpdate {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *ChunkUpdate) AddChunkIndex(v int) *ChunkUpdate {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetChunkHash sets the "chunk_hash" field.
func (_u *ChunkUpdate) SetChunkHash(v string) *ChunkUpdate {
	_u.mutation.SetChunkHash(v)
	return _u
}

// SetNillableChunkHash sets the "chunk_hash" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableChunkHash(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetChunkHash(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChunkUpdate) SetContent(v string) *ChunkUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableContent(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ChunkUpdate) SetEmbedding(v pgvector.HalfVector) *ChunkUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableEmbedding(v *pgvector.HalfVector) *ChunkUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ChunkUpdate) ClearEmbedding() *ChunkUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetProject sets the "project" field.
func (_u *ChunkUpdate) SetProject(v string) *ChunkUpdate {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableProject(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// ClearProject clears the value of the "project" field.
func (_u *ChunkUpdate) ClearProject() *ChunkUpdate {
	_u.mutation.ClearProject()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ChunkUpdate) SetTags(v []string) *ChunkUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ChunkUpdate) AppendTags(v []string) *ChunkUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ChunkUpdate) ClearTags() *ChunkUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetItemDueAt sets the "item_due_at" field.
func (_u *ChunkUpdate) SetItemDueAt(v time.Time) *ChunkUpdate {
	_u.mutation.SetItemDueAt(v)
	return _u
}

// SetNillableItemDueAt sets the "item_due_at" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableItemDueAt(v *time.Time) *ChunkUpdate {
	if v != nil {
		_u.SetItemDueAt(*v)
	}
	return _u
}

// ClearItemDueAt clears the value of the "item_due_at" field.
func (_u *ChunkUpdate) ClearItemDueAt() *ChunkUpdate {
	_u.mutation.ClearItemDueAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChunkUpdate) SetUpdatedAt(v time.Time) *ChunkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChunkMutation object of the builder.
func (_u *ChunkUpdate) Mutation() *ChunkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChunkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChunkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chunk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChunkUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := chunk.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Chunk.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChunkHash(); ok {
		if err := chunk.ChunkHashValidator(v); err != nil {
			return &ValidationError{Name: "chunk_hash", err: fmt.Errorf(`ent: validator failed for field "Chunk.chunk_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Project(); ok {
		if err := chunk.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "Chunk.project": %w`, err)}
		}
	}
	return nil
}

func (_u *ChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(chunk.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(chunk.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(chunk.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(chunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(chunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkHash(); ok {
		_spec.SetField(chunk.FieldChunkHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(chunk.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(chunk.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(chunk.FieldProject, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		_spec.ClearField(chunk.FieldProject, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(chunk.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chunk.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(chunk.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ItemDueAt(); ok {
		_spec.SetField(chunk.FieldItemDueAt, field.TypeTime, value)
	}
	if _u.mutation.ItemDueAtCleared() {
		_spec.ClearField(chunk.FieldItemDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chunk.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChunkUpdateOne is the builder for updating a single Chunk entity.
type ChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChunkMutation
}

// SetSourceType sets the "source_type" field.
func (_u *ChunkUpdateOne) SetSourceType(v chunk.SourceType) *ChunkUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableSourceType(v *chunk.SourceType) *ChunkUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ChunkUpdateOne) SetSourceID(v int) *ChunkUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableSourceID(v *int) *ChunkUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ChunkUpdateOne) AddSourceID(v int) *ChunkUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *ChunkUpdateOne) SetChunkIndex(v int) *ChunkUpdateOne {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableChunkIndex(v *int) *ChunkUpdateOne {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *ChunkUpdateOne) AddChunkIndex(v int) *ChunkUpdateOne {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetChunkHash sets the "chunk_hash" field.
func (_u *ChunkUpdateOne) SetChunkHash(v string) *ChunkUpdateOne {
	_u.mutation.SetChunkHash(v)
	return _u
}

// SetNillableChunkHash sets the "chunk_hash" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableChunkHash(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetChunkHash(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChunkUpdateOne) SetContent(v string) *ChunkUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableContent(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ChunkUpdateOne) SetEmbedding(v pgvector.HalfVector) *ChunkUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableEmbedding(v *pgvector.HalfVector) *ChunkUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ChunkUpdateOne) ClearEmbedding() *ChunkUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetProject sets the "project" field.
func (_u *ChunkUpdateOne) SetProject(v string) *ChunkUpdateOne {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableProject(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// ClearProject clears the value of the "project" field.
func (_u *ChunkUpdateOne) ClearProject() *ChunkUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ChunkUpdateOne) SetTags(v []string) *ChunkUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ChunkUpdateOne) AppendTags(v []string) *ChunkUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ChunkUpdateOne) ClearTags() *ChunkUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetItemDueAt sets the "item_due_at" field.
func (_u *ChunkUpdateOne) SetItemDueAt(v time.Time) *ChunkUpdateOne {
	_u.mutation.SetItemDueAt(v)
	return _u
}

// SetNillableItemDueAt sets the "item_due_at" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableItemDueAt(v *time.Time) *ChunkUpdateOne {
	if v != nil {
		_u.SetItemDueAt(*v)
	}
	return _u
}

// ClearItemDueAt clears the value of the "item_due_at" field.
func (_u *ChunkUpdateOne) ClearItemDueAt() *ChunkUpdateOne {
	_u.mutation.ClearItemDueAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChunkUpdateOne) SetUpdatedAt(v time.Time) *ChunkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ChunkMutation object of the builder.
func (_u *ChunkUpdateOne) Mutation() *ChunkMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChunkUpdate builder.
func (_u *ChunkUpdateOne) Where(ps ...predicate.Chunk) *ChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChunkUpdateOne) Select(field string, fields ...string) *ChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chunk entity.
func (_u *ChunkUpdateOne) Save(ctx context.Context) (*Chunk, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChunkUpdateOne) SaveX(ctx context.Context) *Chunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChunkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chunk.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChunkUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := chunk.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Chunk.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChunkHash(); ok {
		if err := chunk.ChunkHashValidator(v); err != nil {
			return &ValidationError{Name: "chunk_hash", err: fmt.Errorf(`ent: validator failed for field "Chunk.chunk_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Project(); ok {
		if err := chunk.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "Chunk.project": %w`, err)}
		}
	}
	return nil
}

func (_u *ChunkUpdateOne) sqlSave(ctx context.Context) (_node *Chunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chunk.FieldID)
		for _, f := range fields {
			if !chunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(chunk.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(chunk.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(chunk.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(chunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(chunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkHash(); ok {
		_spec.SetField(chunk.FieldChunkHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(chunk.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(chunk.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(chunk.FieldProject, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		_spec.ClearField(chunk.FieldProject, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(chunk.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chunk.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(chunk.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ItemDueAt(); ok {
		_spec.SetField(chunk.FieldItemDueAt, field.TypeTime, value)
	}
	if _u.mutation.ItemDueAtCleared() {
		_spec.ClearField(chunk.FieldItemDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chunk.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Chunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
