// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bamarler/universe-647/sophon/internal/ent/chunk"
	"github.com/bamarler/universe-647/sophon/internal/ent/note"
	"github.com/bamarler/universe-647/sophon/internal/ent/savedfilter"
	"github.com/bamarler/universe-647/sophon/internal/ent/schema"
	"github.com/bamarler/universe-647/sophon/internal/ent/tag"
	"github.com/bamarler/universe-647/sophon/internal/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescChunkIndex is the schema descriptor for chunk_index field.
	chunkDescChunkIndex := chunkFields[2].Descriptor()
	// chunk.DefaultChunkIndex holds the default value on creation for the chunk_index field.
	chunk.DefaultChunkIndex = chunkDescChunkIndex.Default.(int)
	// chunkDescChunkHash is the schema descriptor for chunk_hash field.
	chunkDescChunkHash := chunkFields[3].Descriptor()
	// chunk.ChunkHashValidator is a validator for the "chunk_hash" field. It is called by the builders before save.
	chunk.ChunkHashValidator = chunkDescChunkHash.Validators[0].(func(string) error)
	// chunkDescProject is the schema descriptor for project field.
	chunkDescProject := chunkFields[6].Descriptor()
	// chunk.ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	chunk.ProjectValidator = chunkDescProject.Validators[0].(func(string) error)
	// chunkDescCreatedAt is the schema descriptor for created_at field.
	chunkDescCreatedAt := chunkFields[9].Descriptor()
	// chunk.DefaultCreatedAt holds the default value on creation for the created_at field.
	chunk.DefaultCreatedAt = chunkDescCreatedAt.Default.(func() time.Time)
	// chunkDescUpdatedAt is the schema descriptor for updated_at field.
	chunkDescUpdatedAt := chunkFields[10].Descriptor()
	// chunk.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chunk.DefaultUpdatedAt = chunkDescUpdatedAt.Default.(func() time.Time)
	// chunk.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chunk.UpdateDefaultUpdatedAt = chunkDescUpdatedAt.UpdateDefault.(func() time.Time)
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescTitle is the schema descriptor for title field.
	noteDescTitle := noteFields[0].Descriptor()
	// note.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	note.TitleValidator = func() func(string) error {
		validators := noteDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// noteDescCreatedAt is the schema descriptor for created_at field.
	noteDescCreatedAt := noteFields[2].Descriptor()
	// note.DefaultCreatedAt holds the default value on creation for the created_at field.
	note.DefaultCreatedAt = noteDescCreatedAt.Default.(func() time.Time)
	// noteDescUpdatedAt is the schema descriptor for updated_at field.
	noteDescUpdatedAt := noteFields[3].Descriptor()
	// note.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	note.DefaultUpdatedAt = noteDescUpdatedAt.Default.(func() time.Time)
	// note.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	note.UpdateDefaultUpdatedAt = noteDescUpdatedAt.UpdateDefault.(func() time.Time)
	savedfilterFields := schema.SavedFilter{}.Fields()
	_ = savedfilterFields
	// savedfilterDescName is the schema descriptor for name field.
	savedfilterDescName := savedfilterFields[0].Descriptor()
	// savedfilter.NameValidator is a validator for the "name" field. It is called by the builders before save.
	savedfilter.NameValidator = func() func(string) error {
		validators := savedfilterDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// savedfilterDescCreatedAt is the schema descriptor for created_at field.
	savedfilterDescCreatedAt := savedfilterFields[2].Descriptor()
	// savedfilter.DefaultCreatedAt holds the default value on creation for the created_at field.
	savedfilter.DefaultCreatedAt = savedfilterDescCreatedAt.Default.(func() time.Time)
	// savedfilterDescUpdatedAt is the schema descriptor for updated_at field.
	savedfilterDescUpdatedAt := savedfilterFields[3].Descriptor()
	// savedfilter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	savedfilter.DefaultUpdatedAt = savedfilterDescUpdatedAt.Default.(func() time.Time)
	// savedfilter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	savedfilter.UpdateDefaultUpdatedAt = savedfilterDescUpdatedAt.UpdateDefault.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = func() func(string) error {
		validators := tagDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagFields[4].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagFields[5].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
	// tag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tag.UpdateDefaultUpdatedAt = tagDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[0].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = func() func(string) error {
		validators := taskDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[3].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// task.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	task.PriorityValidator = func() func(int) error {
		validators := taskDescPriority.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(priority int) error {
			for _, fn := range fns {
				if err := fn(priority); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[7].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[8].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
}
