// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bamarler/universe-647/sophon/internal/ent/predicate"
	"github.com/bamarler/universe-647/sophon/internal/ent/savedfilter"
)

// SavedFilterUpdate is the builder for updating SavedFilter entities.
type SavedFilterUpdate struct {
	config
	hooks    []Hook
	mutation *SavedFilterMutation
}

// Where appends a list predicates to the SavedFilterUpdate builder.
func (_u *SavedFilterUpdate) Where(ps ...predicate.SavedFilter) *SavedFilterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SavedFilterUpdate) SetName(v string) *SavedFilterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedFilterUpdate) SetNillableName(v *string) *SavedFilterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *SavedFilterUpdate) SetQuery(v map[string]interface{}) *SavedFilterUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedFilterUpdate) SetUpdatedAt(v time.Time) *SavedFilterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SavedFilterMutation object of the builder.
func (_u *SavedFilterUpdate) Mutation() *SavedFilterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SavedFilterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedFilterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SavedFilterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedFilterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedFilterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedfilter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedFilterUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := savedfilter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedFilter.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SavedFilterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedfilter.Table, savedfilter.Columns, sqlgraph.NewFieldSpec(savedfilter.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedfilter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(savedfilter.FieldQuery, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedfilter.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SavedFilterUpdateOne is the builder for updating a single SavedFilter entity.
type SavedFilterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SavedFilterMutation
}

// SetName sets the "name" field.
func (_u *SavedFilterUpdateOne) SetName(v string) *SavedFilterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedFilterUpdateOne) SetNillableName(v *string) *SavedFilterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *SavedFilterUpdateOne) SetQuery(v map[string]interface{}) *SavedFilterUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedFilterUpdateOne) SetUpdatedAt(v time.Time) *SavedFilterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SavedFilterMutation object of the builder.
func (_u *SavedFilterUpdateOne) Mutation() *SavedFilterMutation {
	return _u.mutation
}

// Where appends a list predicates to the SavedFilterUpdate builder.
func (_u *SavedFilterUpdateOne) Where(ps ...predicate.SavedFilter) *SavedFilterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SavedFilterUpdateOne) Select(field string, fields ...string) *SavedFilterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SavedFilter entity.
func (_u *SavedFilterUpdateOne) Save(ctx context.Context) (*SavedFilter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedFilterUpdateOne) SaveX(ctx context.Context) *SavedFilter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SavedFilterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedFilterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedFilterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedfilter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedFilterUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := savedfilter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedFilter.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SavedFilterUpdateOne) sqlSave(ctx context.Context) (_node *SavedFilter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedfilter.Table, savedfilter.Columns, sqlgraph.NewFieldSpec(savedfilter.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SavedFilter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedfilter.FieldID)
		for _, f := range fields {
			if !savedfilter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != savedfilter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedfilter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(savedfilter.FieldQuery, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedfilter.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SavedFilter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
