// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bamarler/universe-647/sophon/internal/ent/savedfilter"
)

// SavedFilterCreate is the builder for creating a SavedFilter entity.
type SavedFilterCreate struct {
	config
	mutation *SavedFilterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SavedFilterCreate) SetName(v string) *SavedFilterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *SavedFilterCreate) SetQuery(v map[string]interface{}) *SavedFilterCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SavedFilterCreate) SetCreatedAt(v time.Time) *SavedFilterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SavedFilterCreate) SetNillableCreatedAt(v *time.Time) *SavedFilterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SavedFilterCreate) SetUpdatedAt(v time.Time) *SavedFilterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SavedFilterCreate) SetNillableUpdatedAt(v *time.Time) *SavedFilterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SavedFilterMutation object of the builder.
func (_c *SavedFilterCreate) Mutation() *SavedFilterMutation {
	return _c.mutation
}

// Save creates the SavedFilter in the database.
func (_c *SavedFilterCreate) Save(ctx context.Context) (*SavedFilter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedFilterCreate) SaveX(ctx context.Context) *SavedFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedFilterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedFilterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SavedFilterCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := savedfilter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := savedfilter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedFilterCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SavedFilter.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := savedfilter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedFilter.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "SavedFilter.query"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SavedFilter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SavedFilter.updated_at"`)}
	}
	return nil
}

func (_c *SavedFilterCreate) sqlSave(ctx context.Context) (*SavedFilter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedFilterCreate) createSpec() (*SavedFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedFilter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedfilter.Table, sqlgraph.NewFieldSpec(savedfilter.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(savedfilter.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(savedfilter.FieldQuery, field.TypeJSON, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(savedfilter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(savedfilter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SavedFilter.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SavedFilterUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SavedFilterCreate) OnConflict(opts ...sql.ConflictOption) *SavedFilterUpsertOne {
	_c.conflict = opts
	return &SavedFilterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SavedFilterCreate) OnConflictColumns(columns ...string) *SavedFilterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SavedFilterUpsertOne{
		create: _c,
	}
}

type (
	// SavedFilterUpsertOne is the builder for "upsert"-ing
	//  one SavedFilter node.
	SavedFilterUpsertOne struct {
		create *SavedFilterCreate
	}

	// SavedFilterUpsert is the "OnConflict" setter.
	SavedFilterUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SavedFilterUpsert) SetName(v string) *SavedFilterUpsert {
	u.Set(savedfilter.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SavedFilterUpsert) UpdateName() *SavedFilterUpsert {
	u.SetExcluded(savedfilter.FieldName)
	return u
}

// SetQuery sets the "query" field.
func (u *SavedFilterUpsert) SetQuery(v map[string]interface{}) *SavedFilterUpsert {
	u.Set(savedfilter.FieldQuery, v)
	return u
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SavedFilterUpsert) UpdateQuery() *SavedFilterUpsert {
	u.SetExcluded(savedfilter.FieldQuery)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SavedFilterUpsert) SetUpdatedAt(v time.Time) *SavedFilterUpsert {
	u.Set(savedfilter.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SavedFilterUpsert) UpdateUpdatedAt() *SavedFilterUpsert {
	u.SetExcluded(savedfilter.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SavedFilterUpsertOne) UpdateNewValues() *SavedFilterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(savedfilter.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SavedFilterUpsertOne) Ignore() *SavedFilterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SavedFilterUpsertOne) DoNothing() *SavedFilterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SavedFilterCreate.OnConflict
// documentation for more info.
func (u *SavedFilterUpsertOne) Update(set func(*SavedFilterUpsert)) *SavedFilterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SavedFilterUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SavedFilterUpsertOne) SetName(v string) *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SavedFilterUpsertOne) UpdateName() *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateName()
	})
}

// SetQuery sets the "query" field.
func (u *SavedFilterUpsertOne) SetQuery(v map[string]interface{}) *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SavedFilterUpsertOne) UpdateQuery() *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateQuery()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SavedFilterUpsertOne) SetUpdatedAt(v time.Time) *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SavedFilterUpsertOne) UpdateUpdatedAt() *SavedFilterUpsertOne {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SavedFilterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SavedFilterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SavedFilterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SavedFilterUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SavedFilterUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SavedFilterCreateBulk is the builder for creating many SavedFilter entities in bulk.
type SavedFilterCreateBulk struct {
	config
	err      error
	builders []*SavedFilterCreate
	conflict []sql.ConflictOption
}

// Save creates the SavedFilter entities in the database.
func (_c *SavedFilterCreateBulk) Save(ctx context.Context) ([]*SavedFilter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedFilter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedFilterCreateBulk) SaveX(ctx context.Context) []*SavedFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedFilterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SavedFilter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SavedFilterUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SavedFilterCreateBulk) OnConflict(opts ...sql.ConflictOption) *SavedFilterUpsertBulk {
	_c.conflict = opts
	return &SavedFilterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SavedFilterCreateBulk) OnConflictColumns(columns ...string) *SavedFilterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SavedFilterUpsertBulk{
		create: _c,
	}
}

// SavedFilterUpsertBulk is the builder for "upsert"-ing
// a bulk of SavedFilter nodes.
type SavedFilterUpsertBulk struct {
	create *SavedFilterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SavedFilterUpsertBulk) UpdateNewValues() *SavedFilterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(savedfilter.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SavedFilter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SavedFilterUpsertBulk) Ignore() *SavedFilterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SavedFilterUpsertBulk) DoNothing() *SavedFilterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SavedFilterCreateBulk.OnConflict
// documentation for more info.
func (u *SavedFilterUpsertBulk) Update(set func(*SavedFilterUpsert)) *SavedFilterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SavedFilterUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SavedFilterUpsertBulk) SetName(v string) *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SavedFilterUpsertBulk) UpdateName() *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateName()
	})
}

// SetQuery sets the "query" field.
func (u *SavedFilterUpsertBulk) SetQuery(v map[string]interface{}) *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SavedFilterUpsertBulk) UpdateQuery() *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateQuery()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SavedFilterUpsertBulk) SetUpdatedAt(v time.Time) *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SavedFilterUpsertBulk) UpdateUpdatedAt() *SavedFilterUpsertBulk {
	return u.Update(func(s *SavedFilterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SavedFilterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SavedFilterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SavedFilterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SavedFilterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
